baseURL = "https://rojeralone.cn/"
languageCode = "en-us"
title = "RojerAlone"

theme = "m10c"
googleAnalytics = "G-T1VNZF1VBZ"

[params]
  author = 'RojerAlone'
  description = 'Developer'

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/RojerAlone"
